title:              RedBlue's Blog
email:              redblue@red-blue.it
description:        Development page
author:             RedBlue
baseurl:            ""
url:                "https://redblue81.github.io"
remote-theme:       clean-blog
