title:              RedBlue's Blog
email:              redblue81@gmail.com
description:        Development page
author:             RedBlue
baseurl:            ""
url:                "https://redblue81.github.io"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-auto-image
# theme:              jekyll-theme-clean-blog
remote_theme:       StartBootstrap/startbootstrap-clean-blog-jekyll

# Social Profiles
twitter_username:   redblue81
github_username:    redblue81
facebook_username:  angeloredbluepascadopoli
instagram_username: redblue81 
linkedin_username: angelopascadopoli
