title:              RedBlue's Blog
email:              redblue81@gmail.com
description:        Another technology addicted's personal page
author:             RedBlue
baseurl:            ""
url:                "https://red-blue.it"

future: false

paginate: 5
paginate_path: "posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
#  - jekyll-archives
#  - jekyll-auto-image
#theme:              jekyll-theme-clean-blog
remote_theme:       StartBootstrap/startbootstrap-clean-blog-jekyll

google_analytics: 389635826

# Social Profiles
twitter_username:   redblue81
github_username:    redblue81
facebook_username:  angeloredbluepascadopoli
instagram_username: redblue81 
linkedin_username: angelopascadopoli
