name: Build and deploy Jekyll site to GitHub Pages

on:
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v4
        with:
          path: |
            .asdf/**
            vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # 🔧 Fix per certificati SSL e CRL
      - name: Update CA certificates
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates

      # 🔒 Disabilita controllo CRL troppo severo in Ruby/OpenSSL
      - name: Patch Ruby OpenSSL CRL check
        run: echo "RUBYOPT='-ropenssl -e \"OpenSSL::SSL::SSLContext::DEFAULT_PARAMS.delete(:verify_hostname) if defined?(OpenSSL::SSL::SSLContext::DEFAULT_PARAMS)\"'" >> $GITHUB_ENV

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.BLOG_ACTIONS_TOKEN }} 
          branch: 'gh-pages'
          ruby_ver: '3.3.0'
          cname: 'red-blue.it'
          pre_build_commands: git config --global http.postBuffer 157286400
