name: Build and deploy Jekyll site to GitHub Pages

on:
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Disable SSL verification
        run: |
          git config --global http.sslVerify false

      - uses: actions/checkout@v4

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v4
        with:
          path: |
            .asdf/**
            vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.BLOG_ACTIONS_TOKEN }} 
          branch: 'gh-pages'
          cname: 'red-blue.it'
          pre_build_commands: git config --global http.postBuffer 157286400
